/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * Returns a daily reflection prompt and a small kindness action.
 * @summary Get today's kindness practice
 */
export const GetGraceTodayResponse = zod.object({
  "greeting": zod.string(),
  "reflection": zod.string(),
  "action": zod.string(),
  "affirmation": zod.string()
})


/**
 * Returns an empathetic, kindness-focused response to a user's message.
 * @summary Talk with grace.ai
 */
export const sendGraceChatBodyMessageMax = 4000;

export const sendGraceChatBodyHistoryMax = 20;



export const SendGraceChatBody = zod.object({
  "message": zod.string().min(1).max(sendGraceChatBodyMessageMax),
  "history": zod.array(zod.object({
  "role": zod.enum(['user', 'assistant']),
  "content": zod.string()
})).max(sendGraceChatBodyHistoryMax).optional()
})

export const SendGraceChatResponse = zod.object({
  "reply": zod.string(),
  "kindnessNote": zod.string(),
  "crisisSupport": zod.boolean(),
  "supportResources": zod.array(zod.object({
  "label": zod.string(),
  "detail": zod.string(),
  "phone": zod.string()
}))
})


